###
POST http://localhost:9000/api/director HTTP/1.1
Content-Type: application/json

{
    "dir_id": 121,
    "dir_fname": "James",
    "dir_lname": "Cameron"
}

###
GET http://localhost:9000/api/director HTTP/1.1
Accept: application/json

###
GET http://localhost:9000/api/director/212 HTTP/1.1


###
DELETE http://localhost:9000/api/director/121 HTTP/1.1

###
PUT http://localhost:9000/api/director/121 HTTP/1.1
