###
POST http://localhost:9000/api/genres HTTP/1.1
Content-Type: application/json

{
    "gen_id": 6,
    "gen_title": "Comedia"
}

###
GET http://localhost:9000/api/genres HTTP/1.1
Accept: application/json

###
GET http://localhost:9000/api/genres/1001 HTTP/1.1

###
PUT http://localhost:9000/api/genres/10044 HTTP/1.1
Content-Type: application/json

{
    "gen_id": 10044,
    "gen_title": "Biographyy"
}

###
DELETE http://localhost:9000/api/genres/6 HTTP/1.1
