###
POST http://localhost:9000/api/movie_cast HTTP/1.1
Content-Type: application/json

{
    "act_id": 11,
    "mov_id": 15,
    "role": "Miranda Cameron"
}

###
GET http://localhost:9000/api/movie_cast HTTP/1.1
Accept: application/json

###
GET http://localhost:9000/api/movie_cast/63f78c5a9457fe310553318a HTTP/1.1

###
PUT http://localhost:9000/api/movie_cast/101 HTTP/1.1
Content-Type: application/json
{
    "act_id": 11,
    "mov_id": 15,
    "role": "Miranda Cameron"
}

###
DELETE http://localhost:9000/api/genres/11 HTTP/1.1
