###
POST http://localhost:9000/api/movie_genres HTTP/1.1
Content-Type: application/json

{
    "gen_id": 960,
    "mov_id": 1060
}

###
GET http://localhost:9000/api/movie_genres HTTP/1.1
Accept: application/json

###
GET http://localhost:9000/api/movie_genres/991 HTTP/1.1

### 
PUT  http://localhost:9000/api/movie_genres/930 HTTP/1.1
Accept: application/json

{
    "gen_id": 930,
    "mov_id": 1030
}

###
DELETE http://localhost:9000/api/movie_genres/63f8d1ab2d584cde8d906b00 HTTP/1.1



# NO ME SIRVE UN GET NI EL PUT