###

POST http://localhost:9000/api/movies HTTP/1.1
Content-type: application/json

{
    "mov_id": 901,
    "mov_title": "Vertigo",
    "mov_year": 1958,
    "mov_time": 128,
    "mov_lang": "English",
    "mov_dt_rel": "1958-08-24",
    "mov_rel_country": "UK"
}


###

GET http://localhost:9000/api/movies HTTP/1.1
Accept: application/json


###
GET http://localhost:9000/api/movies/905 HTTP/1.1


###
PUT http://localhost:9000/api/movies/903 HTTP/1.1
Content-Type: application/json

{
    "mov_id": 901,
    "mov_title": "LAURA DE ARABIA",
    "mov_year": 1958,
    "mov_time": 128,
    "mov_lang": "English",
    "mov_dt_rel": "1958-08-24",
    "mov_rel_country": "UK"
}

###

DELETE  http://localhost:9000/api/movies/63f81d5997be3b9a5f2e65b0 HTTP/1.1