###
POST http://localhost:9000/api/reviewer HTTP/1.1
Content-Type: application/json

{
    "rev_id": 9005,
    "rev_name": "Jack Masdasdsdern"
}

###
GET http://localhost:9000/api/reviewer HTTP/1.1
Accept: application/json

###
GET http://localhost:9000/api/reviewer/9005 HTTP/1.1

### 
PUT  http://localhost:9000/api/reviewer/9005 HTTP/1.1
Content-Type: application/json

{
    "rev_id": 9003,
    "rev_name": "Legueco maria patricia"
}

###
DELETE http://localhost:9000/api/reviewer/63f8e2fed4358ed2e763202a HTTP/1.1



# NO ME SIRVE UN GET NI EL PUT